version: 2.1

parameters:
  run_build_2:
    type: boolean
    default: false

executors:
  base:
    docker:
        - image: cimg/base:2025.06
  php:
    docker:
      - image: cimg/php:7.4

jobs:
  build:
    executor: base
    steps:
      - checkout
      - run:
          name: Check OS info
          command: cat /etc/os-release
  build2:
    executor: php
    steps:
      - checkout
      - run:
          name: Check OS info
          command: cat /etc/os-release
  test:
    executor: base
    steps:
      - checkout
      - run:
          name: OS info
          command: cat /etc/os-release
  deploy:
    executor: php
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - run: php --version
      - run:
          name: Environment Check
          command: |
            echo "Environment: << parameters.environment >>"

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold_for_approval:
          type: approval
          requires:
            - test
      - deploy:
          environment: DEV
          requires:
            - hold_for_approval
  build2:
    when: << pipeline.parameters.run_build_2 >>
    jobs:
      - build2